baseURL = "https://pmc-hawaii.github.io/"
languageCode = "en-us"
title = "Panditãrãma Meditation Center - Hawaii"
theme = "mytheme"
enableEmoji = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-168250111-1"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    env = "production"
    featured_image = "/sayadawgyi.jpg"
    facebook = "https://www.facebook.com/Panditarama-Meditation-Center-of-Hawaii-799446840208522/"
    twitter = ""
    instagram = ""
    youtube = "https://www.youtube.com/user/Panditarama"
    github = ""
    gitlab = ""
    linkedin = ""
    mastodon = ""
    slack = ""
    stackoverflow = ""
    background_color_class = "bg-mid-gray"
    body_classes = "avenir bg-near-white"