baseURL = "https://pmc-hawaii.github.io/"
languageCode = "en-us"
title = "Panditãrãma Meditation Center - Hawaii"
theme = "mytheme"
enableEmoji = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-168250111-1"

[params]
    featured_image = "/sayadawgyi.jpg"
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    mastodon = ""
    slack = ""
    stackoverflow = ""
    background_color_class = "bg-mid-gray"
    body_classes = "avenir bg-near-white"